name: versus_db

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: versus_db
    ports:
      - 5432:5432
    env_file:
      - .env.development.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres_data:
