/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface Friends {
  user_id_1: string;
  user_id_2: string;
  created_at: string;
}
