/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface FriendRequests {
  friend_request_id: string;
  from_user_id: string;
  to_user_id: string;
  status: string;
  created_at: string;
  responded_at: string;
}
