/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface Games {
  game_id: string;
  name: string;
  description: string;
  thumbnail_url: string;
  min_players: number;
  max_players: number;
  created_at: string;
}
