/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface GameResults {
  result_id: string;
  session_id: string;
  user_id: string;
  game_id: string;
  score: number;
  placement: number;
  won: boolean;
  completed_at: string;
}
