/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */
import type { GameStateState } from './gameStateState';

export interface GameState {
  session_id: string;
  state: GameStateState;
  updated_at: string;
}
