/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface Leaderboards {
  game_id: string;
  user_id: string;
  top_score: number;
  total_wins: number;
  total_games: number;
  win_rate: number;
  updated_at: string;
}
