/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface SessionInvites {
  invite_id: string;
  session_id: string;
  invited_user_id: string;
  invited_by_user_id: string;
  status: string;
  invited_at: string;
  accepted_at: string;
}
