/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface Sessions {
  session_id: string;
  game_id: string;
  host_user_id: string;
  is_private: boolean;
  status: string;
  game_mode: string;
  created_at: string;
  started_at: string;
  completed_at: string;
}
