/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface SessionPlayers {
  session_id: string;
  user_id: string;
  joined_at: string;
}
