/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Game Portal API
 * OpenAPI spec version: 1.0.0
 */

export interface Users {
  user_id: string;
  auth0_id: string;
  username: string;
  bio: string;
  is_visible: boolean;
  last_active_at: string;
  created_at: string;
}
